name: covid_summary
description: A Covid-19 summary.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_hooks: ^0.14.0
  flutter_bloc: ^6.0.5
  flutter_masked_text: ^0.8.0
  intl: ^0.16.1
  google_fonts: ^1.1.0
  json_annotation: ^3.0.1
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0
  dio: ^3.0.10
  equatable: ^1.2.0
  flutter_modular: ^2.0.0+1
  flutter:
    sdk: flutter


dev_dependencies:
  freezed: ^0.11.6
  json_serializable: ^3.4.1
  build_runner: ^1.10.0
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

scripts:
  gwatch: flutter pub run build_runner watch

flutter:
  uses-material-design: true